name: Post push check

on:
    push:
    pull_request:
        types: [opened, reopened]

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            # Переключение на выбранную при запуске action ветку и скачивание файлов в окружение.
            - name: Checkout
              uses: actions/checkout@v3

            # Установка зависимостей.
            - name: Install dependencies
              run: yarn

            # Прогон тестов
            - name: Run tests
              run: yarn test

            # Прогон линтера
            - name: Run linter
              id: lint
              run: |
                  set +e
                  OUTPUT=$(yarn lint 2>&1)
                  EXIT_CODE=$?

                  echo "$OUTPUT"

                  echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

                  echo "result<<EOF" >> $GITHUB_OUTPUT
                  echo "$OUTPUT" >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            # Проверка форматирования
            - name: Run format check
              id: format
              run: |
                  set +e
                  yarn format:check
                  EXIT_CODE=$?
                  echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

            # Комментарий в ПР или в консоль workflow
            - name: Comment lint result
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GH_TOKEN }}
                  script: |
                      const commentBody =
                      `### Checks issues
                      \`\`\`
                      ${process.env.LINT_RESULT}
                      \`\`\``;

                      console.log('commentBody', commentBody)
                      const { owner, repo } = context.repo

                      console.log('owner', owner)
                      console.log('repo', repo)

                      const branch = (process.env.GITHUB_REF || '').replace('refs/heads/', '');
                      console.log('branch', branch)

                      if (!branch) {
                        console.log('Не удалось определить ветку, вывод линта:');
                        console.log(commentBody);
                        return;
                      }

                      const prs = await github.rest.pulls.list({
                        owner,
                        repo,
                        head: `${owner}:${branch}`,
                        state: 'open'
                      })
                      console.log('prs', prs)
                      const pr = prs.data[0]

                      if (!pr) {
                        console.log('PR не найден, вывод линта:');
                        console.log(commentBody)
                        return
                      }

                      await github.rest.issues.createComment({
                        owner,
                        repo,
                        issue_number: pr.number,
                        body: commentBody
                      });

              env:
                  LINT_RESULT: ${{ steps.lint.outputs.result }}
                  BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
                  BOT_TOKEN: ${{ secrets.GH_TOKEN }}
                  REPOSITORY: ${{ github.repository }}

            # Блокировка ПР при наличии ошибок линтера или ошибок форматирования
            - name: Block PR if checks failed
              if: steps.lint.outcome != 'success' || steps.format.outcome != 'success'
              run: |
                  echo "CI failed"
                  exit 1

            # Выпуск beta версии библиотеки, если в commit message есть вхождение строки "deploy_beta"
            - name: Publish beta version
              if: "contains(github.event.head_commit.message, 'deploy_beta')"
              run: |
                  CURRENT_VERSION=$(jq -r '.version' package.json)
                  SHORT_SHA=$(git rev-parse --short HEAD)
                  NEW_VERSION="${CURRENT_VERSION}-beta.${SHORT_SHA}"
                  export TAG="beta"
                  export VERSION="$NEW_VERSION"

                  echo "//registry.npmjs.org/:_authToken=$TOKEN" > .npmrc

                  tmp=$(mktemp)
                  jq --arg v "$NEW_VERSION" '.version = $v' package.json > "$tmp" && mv "$tmp" package.json

                  yarn release

                  echo "### Выпущена новая версия библиотеки: $VERSION" >> $GITHUB_STEP_SUMMARY
              env:
                  TOKEN: ${{ secrets.NPM_TOKEN }}
